language: node_js

node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
    - node_modules

script:
  - npm run build && npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
on:
  branch: master
